apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: localhost:5002/transaction-service  # نام Docker Image شما
        ports:
        - containerPort: 5002
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/mydatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
  - protocol: TCP
    port: 8005  # پورت خارجی
    targetPort: 5002  # پورت داخلی
  type: LoadBalancer