apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: localhost:5001/inventory-service  # نام Docker Image شما
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/mydatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
  - protocol: TCP
    port: 8000  # پورت خارجی
    targetPort: 5001  # پورت داخلی
  type: LoadBalancer